---
title: "Result"
author: "Shadi"
date: "2023-07-06"
output:
  pdf_document:
    keep_tex: true
    includes:
      in_header: "preamble.tex"
---


```{r wd-setup, include=FALSE}

wd <- list()
# commonly used paths in my working directory
wd$data   <- "~/Desktop/shadi/Data/"
wd$output <- "~/Desktop/shadi/output/"
wd$texts <- "~/Desktop/shadi/text"
wd$codes <- "~/Desktop/shadi/codes/R/"

```

```{r setup , include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      fig.width = 4, 
                      fig.height = 4, 
                      fig.pos = "H", out.extra = "" ,
                      fig.path = wd$output,
                      dev = "png",
                      dpi = 200,
                      warning=FALSE, 
                      message=FALSE
                      )


```

```{r data-setup}

Data<-read.csv( paste0(wd$data,"CLNACS.csv"), header = TRUE, sep = ",", fill = TRUE, stringsAsFactors = TRUE)
#Forgn<- Data[Data$NATIVITY == "Foregin-born", ]
#NATV<- Data[Data$NATIVITY == "US-born", ]

controls <- c("SEX","DIS", "AGEP","MARG", "SCHLG", "RACE1","ESRG","POVPIPG",'CIT')
foriegn <- c( "ENG", "LTINU", "CORIGIN" )
adjs<-c("UnempR", "ADA")
adj12<-c("UnempR", "ADA","IPC")
```


## Descriptive Analysis

```{r descriptive ,child = 'Descriptive.Rmd'}

```

## Finding Causal Diagram

```{r DAG, child = 'DAG.Rmd'}
```


## Event Study and Parallel Trend Assumption

```{r event-study, child = 'event-study.Rmd'}

```

##  Difference-in-Differences Model Results

```{r did-regression, child = 'did-regression.Rmd'}

```


## Sensitivity and Robustness Check

```{r robustness, child = 'robustness.Rmd'}

```


